import time

def Epic():
    for i in range(100):
        print("")
    print("⠀⠀⠀⣀⣶⣀")
    print("⠀⠀⠀⠒⣛⣭")
    print("⠀⠀⠀⣀⠿⣿⣶")
    print("⠀⣤⣿⠤⣭⣿⣿")
    print("⣤⣿⣿⣿⠛⣿⣿⠀⣀")
    print("⠀⣀⠤⣿⣿⣶⣤⣒⣛")
    print("⠉⠀⣀⣿⣿⣿⣿⣭⠉")
    print("⠀⠀⣭⣿⣿⠿⠿⣿")
    print("⠀⣶⣿⣿⠛⠀⣿⣿")
    print("⣤⣿⣿⠉⠤⣿⣿⠿")
    print("⣿⣿⠛⠀⠿⣿⣿")
    print("⣿⣿⣤⠀⣿⣿⠿")
    print("⠀⣿⣿⣶⠀⣿⣿⣶")
    print("⠀⠀⠛⣿⠀⠿⣿⣿")
    print("⠀⠀⠀⣉⣿⠀⣿⣿")
    print("⠀⠶⣶⠿⠛⠀⠉⣿")
    print("⠀⠀⠀⠀⠀⠀⣀⣿")
    print("⠀⠀⠀⠀⠀⣶⣿⠿")
    print("")
    print("")
    time.sleep(0.7)
    Dance2()


def Dance2():
    for i in range(100):
        print("")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⣤⣿⣿⠶⠀⠀⣀⣀")
    print("⠀⠀⠀⠀⠀⠀⣀⣀⣤⣤⣶⣿⣿⣿⣿⣿⣿")
    print("⠀⠀⣀⣶⣤⣤⠿⠶⠿⠿⠿⣿⣿⣿⣉⣿⣿")
    print("⠿⣉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⣤⣿⣿⣿⣀")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⣿⣿⣶⣤")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣿⣿⣿⣿⠿⣛⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠛⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣶⣿⣿⠿⠀⣿⣿⣿⠛")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠀⠀⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠿⠿⣿⠀⠀⣿⣶")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠛⠀⠀⣿⣿⣶")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⠤")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣀")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣶⣿")
    print("")
    print("")
    time.sleep(0.7)
    Dance3()


def Dance3():
    for i in range(100):
        print("")
    print("⠀⠀⣀")
    print("⠀⠿⣿⣿⣀")
    print("⠀⠉⣿⣿⣀")
    print("⠀⠀⠛⣿⣭⣀⣀⣤")
    print("⠀⠀⣿⣿⣿⣿⣿⠛⠿⣶⣀")
    print("⠀⣿⣿⣿⣿⣿⣿⠀⠀⠀⣉⣶")
    print("⠀⠀⠉⣿⣿⣿⣿⣀⠀⠀⣿⠉")
    print("⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿")
    print("⠀⣀⣿⣿⣿⣿⣿⣿⣿⣿⠿")
    print("⠀⣿⣿⣿⠿⠉⣿⣿⣿⣿")
    print("⠀⣿⣿⠿⠀⠀⣿⣿⣿⣿")
    print("⣶⣿⣿⠀⠀⠀⠀⣿⣿⣿")
    print("⠛⣿⣿⣀⠀⠀⠀⣿⣿⣿⣿⣶⣀")
    print("⠀⣿⣿⠉⠀⠀⠀⠉⠉⠉⠛⠛⠿⣿⣶")
    print("⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣿")
    print("⠀⠀⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉")
    print("⣀⣶⣿⠛")
    print("")
    print("")
    time.sleep(0.7)
    Dance4()


def Dance4():
    for i in range(100):
      print("")
    print("⠀⠀⠀⠀⠀⠀⠀⣀⣀")
    print("⠀⠀⠀⠀⠀⠀⣿⣿⣿⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣤⣿")
    print("⠀⠀⠀⠀⠀⠀⣤⣿⠿⣿⣿⣿⣿⣿⠀⠀⠉")
    print("⠛⣿⣤⣤⣀⣤⠿⠉⠀⠉⣿⣿⣿⣿")
    print("⠀⠉⠉⠉⠉⠉⠀⠀⠀⠀⠉⣿⣿⣿⣀")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣶⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⠛")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣛⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⣶⣿⣿⠛⠿⣿⣿⣿⣶⣤")
    print("⠀⠀⠀⠀⠀⠀⠀⣿⠛⠉⠀⠀⠀⠛⠿⣿⣿⣶⣀")
    print("⠀⠀⠀⠀⠀⠀⣿⣀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠿⣶⣤")
    print("⠀⠀⠀⠀⠀⠛⠿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣿⣿⠿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠉⠉")
    print("")
    print("")
    time.sleep(0.7)
    Dance5()


def Dance5():
    for i in range(100):
        print("")
    print("⠀⠀⠀⠀⠀⠀⣤⣶⣶")
    print("⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣀⣀")
    print("⠀⠀⠀⠀⠀⣀⣶⣿⣿⣿⣿⣿⣿")
    print("⣤⣶⣀⠿⠶⣿⣿⣿⠿⣿⣿⣿⣿")
    print("⠉⠿⣿⣿⠿⠛⠉⠀⣿⣿⣿⣿⣿")
    print("⠀⠀⠉⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣤⣤")
    print("⠀⠀⠀⠀⠀⠀⠀⣤⣶⣿⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⣀⣿⣿⣿⣿⣿⠿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⣀⣿⣿⣿⠿⠉⠀⠀⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⣿⣿⠿⠉⠀⠀⠀⠀⠿⣿⣿⠛")
    print("⠀⠀⠀⠀⠛⣿⣿⣀⠀⠀⠀⠀⠀⣿⣿⣀")
    print("⠀⠀⠀⠀⠀⣿⣿⣿⠀⠀⠀⠀⠀⠿⣿⣿")
    print("⠀⠀⠀⠀⠀⠉⣿⣿⠀⠀⠀⠀⠀⠀⠉⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⣀⣿")
    print("⠀⠀⠀⠀⠀⠀⣀⣿⣿")
    print("⠀⠀⠀⠀⠤⣿⠿⠿⠿")
    print("")
    print("")
    time.sleep(0.7)
    Dance6()


def Dance6():
    for i in range(100):
        print("")
    print("⠀⠀⠀⠀⣀")
    print("⠀⠀⣶⣿⠿⠀⠀⠀⣀⠀⣤⣤")
    print("⠀⣶⣿⠀⠀⠀⠀⣿⣿⣿⠛⠛⠿⣤⣀")
    print("⣶⣿⣤⣤⣤⣤⣤⣿⣿⣿⣀⣤⣶⣭⣿⣶⣀")
    print("⠉⠉⠉⠛⠛⠿⣿⣿⣿⣿⣿⣿⣿⠛⠛⠿⠿")
    print("⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⠿")
    print("⠀⠀⠀⠀⠀⠀⠀⠿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⣭⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⣤⣿⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⠿")
    print("⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⠿")
    print("⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⣿⠛⠿⣿⣤")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣿⠀⠀⠀⣿⣿⣤")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⣶⣿⠛⠉")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⣤⣿⣿⠀⠀⠉")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉")
    print("")
    print("")
    time.sleep(0.7)
    Dance7()


def Dance7():
    for i in range(100):
        print("")
    print("⠀⠀⠀⠀⠀⠀⣶⣿⣶")
    print("⠀⠀⠀⣤⣤⣤⣿⣿⣿")
    print("⠀⠀⣶⣿⣿⣿⣿⣿⣿⣿⣶")
    print("⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿")
    print("⠀⠀⣿⣉⣿⣿⣿⣿⣉⠉⣿⣶")
    print("⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⠿⣿")
    print("⠀⣤⣿⣿⣿⣿⣿⣿⣿⠿⠀⣿⣶")
    print("⣤⣿⠿⣿⣿⣿⣿⣿⠿⠀⠀⣿⣿⣤")
    print("⠉⠉⠀⣿⣿⣿⣿⣿⠀⠀⠒⠛⠿⠿⠿")
    print("⠀⠀⠀⠉⣿⣿⣿⠀⠀⠀⠀⠀⠀⠉")
    print("⠀⠀⠀⣿⣿⣿⣿⣿⣶")
    print("⠀⠀⠀⠀⣿⠉⠿⣿⣿")
    print("⠀⠀⠀⠀⣿⣤⠀⠛⣿⣿")
    print("⠀⠀⠀⠀⣶⣿⠀⠀⠀⣿⣶")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣭⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⣤⣿⣿⠉")
    print("")
    print("")
    time.sleep(0.7)
    Dance8()


def Dance8():
    for i in range(100):
        print("")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣶")
    print("⠀⠀⠀⠀⠀⣀⣀⠀⣶⣿⣿⠶")
    print("⣶⣿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣤⣤")
    print("⠀⠉⠶⣶⣀⣿⣿⣿⣿⣿⣿⣿⠿⣿⣤⣀")
    print("⠀⠀⠀⣿⣿⠿⠉⣿⣿⣿⣿⣭⠀⠶⠿⠿")
    print("⠀⠀⠛⠛⠿⠀⠀⣿⣿⣿⣉⠿⣿⠶")
    print("⠀⠀⠀⠀⠀⣤⣶⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⠒")
    print("⠀⠀⠀⠀⣀⣿⣿⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⣿⣿⣿⠛⣭⣭⠉")
    print("⠀⠀⠀⠀⠀⣿⣿⣭⣤⣿⠛")
    print("⠀⠀⠀⠀⠀⠛⠿⣿⣿⣿⣭")
    print("⠀⠀⠀⠀⠀⠀⠀⣿⣿⠉⠛⠿⣶⣤")
    print("⠀⠀⠀⠀⠀⠀⣀⣿⠀⠀⣶⣶⠿⠿⠿")
    print("⠀⠀⠀⠀⠀⠀⣿⠛")
    print("⠀⠀⠀⠀⠀⠀⣭⣶")
    print("")
    print("")
    time.sleep(0.7)
    Dance9()


def Dance9():
    for i in range(100):
        print("")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣤")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿")
    print("⠀⠀⣶⠀⠀⣀⣤⣶⣤⣉⣿⣿⣤⣀")
    print("⠤⣤⣿⣤⣿⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣀")
    print("⠀⠛⠿⠀⠀⠀⠀⠉⣿⣿⣿⣿⣿⠉⠛⠿⣿⣤")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠿⣿⣿⣿⠛⠀⠀⠀⣶⠿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⣀⣿⣿⣿⣿⣤⠀⣿⠿")
    print("⠀⠀⠀⠀⠀⠀⠀⣶⣿⣿⣿⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠿⣿⣿⣿⣿⣿⠿⠉⠉")
    print("⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⣿⣿⠿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠉")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⣛⣿⣭⣶⣀")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⠉⠛⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⠀⠀⣿⣿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣉⠀⣶⠿")
    print("⠀⠀⠀⠀⠀⠀⠀⠀⣶⣿⠿")
    print("⠀⠀⠀⠀⠀⠀⠀⠛⠿⠛")
    print("")
    print("")
    time.sleep(0.7)
    Dance10()


def Dance10():
    for i in range(100):
        print("")
    print("⠀⠀⠀⣶⣿⣶")
    print("⠀⠀⠀⣿⣿⣿⣀")
    print("⠀⣀⣿⣿⣿⣿⣿⣿")
    print("⣶⣿⠛⣭⣿⣿⣿⣿")
    print("⠛⠛⠛⣿⣿⣿⣿⠿")
    print("⠀⠀⠀⠀⣿⣿⣿")
    print("⠀⠀⣀⣭⣿⣿⣿⣿⣀")
    print("⠀⠤⣿⣿⣿⣿⣿⣿⠉")
    print("⠀⣿⣿⣿⣿⣿⣿⠉")
    print("⣿⣿⣿⣿⣿⣿")
    print("⣿⣿⣶⣿⣿")
    print("⠉⠛⣿⣿⣶⣤")
    print("⠀⠀⠉⠿⣿⣿⣤")
    print("⠀⠀⣀⣤⣿⣿⣿")
    print("⠀⠒⠿⠛⠉⠿⣿")
    print("⠀⠀⠀⠀⠀⣀⣿⣿")
    print("⠀⠀⠀⠀⣶⠿⠿⠛")
    print("")
    print("")
    time.sleep(5)


Epic()
